"""Initial migration

Revision ID: 7e41cbd95d65
Revises: 
Create Date: 2026-02-23 12:17:13.166401

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7e41cbd95d65'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calculations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('principal', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('annual_interest_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tenure_months', sa.Integer(), nullable=False),
    sa.Column('emi', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_interest', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_payment', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('prepayment_used', sa.Boolean(), nullable=True),
    sa.Column('prepayment_data', sa.JSON(), nullable=True),    sa.Column('comparison_group_id', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calculations', schema=None) as batch_op:
        batch_op.create_index('idx_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_principal_rate', ['principal', 'annual_interest_rate'], unique=False)
        batch_op.create_index(batch_op.f('ix_calculations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_calculations_user_id'), ['user_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('subscription_tier', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('calculations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calculations_user_id'))
        batch_op.drop_index(batch_op.f('ix_calculations_created_at'))
        batch_op.drop_index('idx_principal_rate')
        batch_op.drop_index('idx_created_at')

    op.drop_table('calculations')
    # ### end Alembic commands ###
